name: Upload to Google Drive

on:
  push:
    branches:
      - main # Chạy khi có code mới đẩy lên nhánh main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Nén toàn bộ source code thành file zip để dễ upload
      - name: Zip Workspace
        run: zip -r release.zip . -x "*.git*"

      # Sử dụng Action để đẩy lên GDrive
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "release.zip"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true" # Ghi đè file cũ nếu trùng tên
